name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' 
      - run: npm ci
      - run: npm run lint   
      # - run: npm run test      

  build_and_deploy:
    runs-on: ubuntu-latest
    needs: lint_and_test
    outputs:
      sha_short: ${{ steps.vars.outputs.sha_short }}
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Declare variables
        id: vars
        shell: bash
        run: echo "::set-output name=sha_short::$(git rev-parse --short ${GITHUB_SHA})" 

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: deploy
        run: |
          aws s3 sync ./dist s3://${{ secrets.S3_BUCKET }}

      